
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x7f(!\xdd\xdeB\xe1\x8f\xc0E8\x1b9\x13\x06A'
    
_lr_action_items = {'COLON':([1,2,4,8,9,10,11,12,13,14,18,19,20,21,22,23,24,29,30,31,32,33,34,37,38,39,40,41,42,43,44,46,47,48,],[-7,-39,-18,-17,-38,-29,-31,-30,18,-28,-35,-37,-33,-34,-36,-32,29,-39,39,-21,-27,-20,-19,-8,-39,-39,-22,-25,-23,-24,-26,18,-39,18,]),'$end':([0,1,2,3,4,5,6,8,9,10,11,12,13,14,18,19,20,21,22,23,29,30,31,32,33,34,37,38,39,40,41,42,43,44,46,47,48,],[-39,-7,-39,0,-18,-5,-6,-17,-38,-29,-31,-30,-40,-28,-35,-37,-33,-34,-36,-32,-39,-4,-21,-27,-20,-19,-8,-39,-39,-22,-25,-23,-24,-26,-2,-3,-1,]),'DOT':([1,2,4,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,27,28,29,30,31,32,33,34,37,38,39,40,41,42,43,44,46,47,48,],[-7,10,-18,-17,-38,-29,-31,-30,20,-28,-12,26,-35,-37,-33,-34,-36,-32,33,-11,-14,-13,-39,42,-21,-27,-20,-19,-8,10,-39,-22,-25,-23,-24,-26,20,10,20,]),'WS':([0,1,2,4,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,],[4,8,-39,-18,-17,-38,-29,-31,-30,21,-28,4,-12,27,-35,-37,-33,-34,-36,-32,8,-11,-10,-14,-13,4,43,-21,-27,-20,-19,-9,-16,-8,-39,4,-22,-25,-23,-24,-26,-15,21,-39,21,]),'SHARP':([1,2,4,8,9,10,11,12,13,14,18,19,20,21,22,23,24,29,30,31,32,33,34,37,38,39,40,41,42,43,44,46,47,48,],[-7,12,-18,-17,-38,-29,-31,-30,22,-28,-35,-37,-33,-34,-36,-32,31,-39,41,-21,-27,-20,-19,-8,12,-39,-22,-25,-23,-24,-26,22,12,22,]),'SYMBOL':([0,1,2,4,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,],[-39,-7,14,-18,-8,16,-17,-38,-29,-31,-30,23,-28,-12,28,-35,-37,-33,-34,-36,-32,34,-11,36,-14,-13,-39,40,-21,-27,-20,-19,45,-16,-8,14,-39,-22,-25,-23,-24,-26,-15,23,14,23,]),'TILD':([0,],[2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[3,]),'wss':([0,15,29,39,],[1,24,1,1,]),'second_part':([26,],[35,]),'caption':([0,],[5,]),'comment_symbol_1':([2,38,47,],[9,9,9,]),'name':([7,],[15,]),'value_1':([24,],[32,]),'first_part':([7,],[17,]),'comment_symbol':([13,46,48,],[19,19,19,]),'empty':([0,2,29,38,39,47,],[6,11,37,11,37,11,]),'value_rest':([30,],[44,]),'first_part_term':([17,],[25,]),'comment':([2,38,47,],[13,46,48,]),'value':([24,],[30,]),'opt_wss':([0,29,39,],[7,38,47,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> opt_wss name wss value COLON opt_wss comment','line',7,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',53),
  ('line -> opt_wss name wss COLON opt_wss comment','line',6,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',54),
  ('line -> opt_wss name wss value COLON opt_wss','line',6,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',55),
  ('line -> opt_wss name wss value','line',4,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',56),
  ('line -> caption','line',1,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',57),
  ('line -> empty','line',1,'p_line','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',58),
  ('opt_wss -> wss','opt_wss',1,'p_optional_wss','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',113),
  ('opt_wss -> empty','opt_wss',1,'p_optional_wss','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',114),
  ('name -> first_part DOT second_part','name',3,'p_name','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',120),
  ('name -> first_part DOT','name',2,'p_name','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',121),
  ('first_part -> first_part first_part_term','first_part',2,'p_first_part','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',130),
  ('first_part -> SYMBOL','first_part',1,'p_first_part','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',131),
  ('first_part_term -> SYMBOL','first_part_term',1,'p_first_part_term','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',139),
  ('first_part_term -> WS','first_part_term',1,'p_first_part_term','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',140),
  ('second_part -> second_part SYMBOL','second_part',2,'p_second_part','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',149),
  ('second_part -> SYMBOL','second_part',1,'p_second_part','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',150),
  ('wss -> wss WS','wss',2,'p_wss','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',158),
  ('wss -> WS','wss',1,'p_wss','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',159),
  ('value_1 -> SYMBOL','value_1',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',168),
  ('value_1 -> DOT','value_1',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',169),
  ('value_1 -> SHARP','value_1',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',170),
  ('value_rest -> SYMBOL','value_rest',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',171),
  ('value_rest -> DOT','value_rest',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',172),
  ('value_rest -> WS','value_rest',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',173),
  ('value_rest -> SHARP','value_rest',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',174),
  ('value -> value value_rest','value',2,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',175),
  ('value -> value_1','value',1,'p_value','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',176),
  ('comment_symbol_1 -> SYMBOL','comment_symbol_1',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',184),
  ('comment_symbol_1 -> DOT','comment_symbol_1',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',185),
  ('comment_symbol_1 -> SHARP','comment_symbol_1',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',186),
  ('comment_symbol_1 -> empty','comment_symbol_1',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',187),
  ('comment_symbol -> SYMBOL','comment_symbol',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',188),
  ('comment_symbol -> DOT','comment_symbol',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',189),
  ('comment_symbol -> WS','comment_symbol',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',190),
  ('comment_symbol -> COLON','comment_symbol',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',191),
  ('comment_symbol -> SHARP','comment_symbol',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',192),
  ('comment -> comment comment_symbol','comment',2,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',193),
  ('comment -> comment_symbol_1','comment',1,'p_comment','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',194),
  ('empty -> <empty>','empty',0,'p_empty','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',203),
  ('caption -> TILD comment','caption',2,'p_caption','/mnt/963GB/Data/Python/Workspaces/PyCharm/qr/lasio/pylasdev/las_lex_pars2.py',208),
]
