# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logservicelaswizardpage.ui'
#
# Created: Mon Dec 29 19:44:55 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LogServiceLasWizardPage(object):
    def setupUi(self, LogServiceLasWizardPage):
        LogServiceLasWizardPage.setObjectName(_fromUtf8("LogServiceLasWizardPage"))
        LogServiceLasWizardPage.resize(574, 588)
        self.verticalLayout = QtGui.QVBoxLayout(LogServiceLasWizardPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.upperGroupBox = QtGui.QGroupBox(LogServiceLasWizardPage)
        self.upperGroupBox.setTitle(_fromUtf8(""))
        self.upperGroupBox.setObjectName(_fromUtf8("upperGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.upperGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newLogSetRadioButton = QtGui.QRadioButton(self.upperGroupBox)
        self.newLogSetRadioButton.setObjectName(_fromUtf8("newLogSetRadioButton"))
        self.horizontalLayout.addWidget(self.newLogSetRadioButton)
        self.newLogSetNameLineEdit = QtGui.QLineEdit(self.upperGroupBox)
        self.newLogSetNameLineEdit.setObjectName(_fromUtf8("newLogSetNameLineEdit"))
        self.horizontalLayout.addWidget(self.newLogSetNameLineEdit)
        self.existingLogSetRadioButton = QtGui.QRadioButton(self.upperGroupBox)
        self.existingLogSetRadioButton.setObjectName(_fromUtf8("existingLogSetRadioButton"))
        self.horizontalLayout.addWidget(self.existingLogSetRadioButton)
        self.existingLogSetComboBox = QtGui.QComboBox(self.upperGroupBox)
        self.existingLogSetComboBox.setObjectName(_fromUtf8("existingLogSetComboBox"))
        self.horizontalLayout.addWidget(self.existingLogSetComboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.upperGroupBox)
        self.scrollArea = QtGui.QScrollArea(LogServiceLasWizardPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 560, 492))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.logStepLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStepLabel.setObjectName(_fromUtf8("logStepLabel"))
        self.gridLayout_3.addWidget(self.logStepLabel, 4, 0, 1, 1)
        self.analysisByLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.analysisByLineEdit.setObjectName(_fromUtf8("analysisByLineEdit"))
        self.gridLayout_3.addWidget(self.analysisByLineEdit, 0, 1, 1, 2)
        self.defaultRwLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.defaultRwLabel.setObjectName(_fromUtf8("defaultRwLabel"))
        self.gridLayout_3.addWidget(self.defaultRwLabel, 1, 0, 1, 1)
        self.analysisLocationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.analysisLocationLineEdit.setObjectName(_fromUtf8("analysisLocationLineEdit"))
        self.gridLayout_3.addWidget(self.analysisLocationLineEdit, 0, 4, 1, 3)
        self.defaultRwLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.defaultRwLineEdit.setObjectName(_fromUtf8("defaultRwLineEdit"))
        self.gridLayout_3.addWidget(self.defaultRwLineEdit, 1, 1, 1, 2)
        self.defaultRwUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.defaultRwUnitLabel.setObjectName(_fromUtf8("defaultRwUnitLabel"))
        self.gridLayout_3.addWidget(self.defaultRwUnitLabel, 1, 3, 1, 1)
        self.analysisByLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.analysisByLabel.setObjectName(_fromUtf8("analysisByLabel"))
        self.gridLayout_3.addWidget(self.analysisByLabel, 0, 0, 1, 1)
        self.defaultRwtLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.defaultRwtLabel.setObjectName(_fromUtf8("defaultRwtLabel"))
        self.gridLayout_3.addWidget(self.defaultRwtLabel, 2, 0, 1, 1)
        self.defaultRwtLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.defaultRwtLineEdit.setObjectName(_fromUtf8("defaultRwtLineEdit"))
        self.gridLayout_3.addWidget(self.defaultRwtLineEdit, 2, 1, 1, 1)
        self.defaultRwtUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.defaultRwtUnitLabel.setObjectName(_fromUtf8("defaultRwtUnitLabel"))
        self.gridLayout_3.addWidget(self.defaultRwtUnitLabel, 2, 3, 1, 1)
        self.analysisLocationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.analysisLocationLabel.setObjectName(_fromUtf8("analysisLocationLabel"))
        self.gridLayout_3.addWidget(self.analysisLocationLabel, 0, 3, 1, 1)
        self.tdLoggerLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tdLoggerLabel.setObjectName(_fromUtf8("tdLoggerLabel"))
        self.gridLayout_3.addWidget(self.tdLoggerLabel, 11, 0, 1, 1)
        self.logStartLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.logStartLineEdit.setObjectName(_fromUtf8("logStartLineEdit"))
        self.gridLayout_3.addWidget(self.logStartLineEdit, 3, 1, 1, 1)
        self.logStartUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStartUnitLabel.setObjectName(_fromUtf8("logStartUnitLabel"))
        self.gridLayout_3.addWidget(self.logStartUnitLabel, 3, 3, 1, 1)
        self.logStartLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStartLabel.setObjectName(_fromUtf8("logStartLabel"))
        self.gridLayout_3.addWidget(self.logStartLabel, 3, 0, 1, 1)
        self.tdLoggerUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.tdLoggerUnitComboBox.setObjectName(_fromUtf8("tdLoggerUnitComboBox"))
        self.gridLayout_3.addWidget(self.tdLoggerUnitComboBox, 11, 5, 1, 1)
        self.loggingReferenceLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.loggingReferenceLabel.setObjectName(_fromUtf8("loggingReferenceLabel"))
        self.gridLayout_3.addWidget(self.loggingReferenceLabel, 8, 0, 1, 1)
        self.logStepUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStepUnitLabel.setObjectName(_fromUtf8("logStepUnitLabel"))
        self.gridLayout_3.addWidget(self.logStepUnitLabel, 4, 3, 1, 1)
        self.logStepLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.logStepLineEdit.setObjectName(_fromUtf8("logStepLineEdit"))
        self.gridLayout_3.addWidget(self.logStepLineEdit, 4, 1, 1, 1)
        self.nullValueLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.nullValueLineEdit.setObjectName(_fromUtf8("nullValueLineEdit"))
        self.gridLayout_3.addWidget(self.nullValueLineEdit, 8, 5, 1, 1)
        self.runNumberLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.runNumberLabel.setObjectName(_fromUtf8("runNumberLabel"))
        self.gridLayout_3.addWidget(self.runNumberLabel, 9, 0, 1, 1)
        self.depthDomainComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.depthDomainComboBox.setObjectName(_fromUtf8("depthDomainComboBox"))
        self.gridLayout_3.addWidget(self.depthDomainComboBox, 13, 5, 1, 1)
        self.logStopLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStopLabel.setObjectName(_fromUtf8("logStopLabel"))
        self.gridLayout_3.addWidget(self.logStopLabel, 6, 0, 1, 1)
        self.logStopUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logStopUnitLabel.setObjectName(_fromUtf8("logStopUnitLabel"))
        self.gridLayout_3.addWidget(self.logStopUnitLabel, 6, 3, 1, 1)
        self.logStopLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.logStopLineEdit.setObjectName(_fromUtf8("logStopLineEdit"))
        self.gridLayout_3.addWidget(self.logStopLineEdit, 6, 1, 1, 1)
        self.depthDomainLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.depthDomainLabel.setObjectName(_fromUtf8("depthDomainLabel"))
        self.gridLayout_3.addWidget(self.depthDomainLabel, 13, 3, 1, 1)
        self.loggingReferenceLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.loggingReferenceLineEdit.setObjectName(_fromUtf8("loggingReferenceLineEdit"))
        self.gridLayout_3.addWidget(self.loggingReferenceLineEdit, 8, 1, 1, 1)
        self.nullValueLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.nullValueLabel.setObjectName(_fromUtf8("nullValueLabel"))
        self.gridLayout_3.addWidget(self.nullValueLabel, 8, 3, 1, 1)
        self.runNumberLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.runNumberLineEdit.setObjectName(_fromUtf8("runNumberLineEdit"))
        self.gridLayout_3.addWidget(self.runNumberLineEdit, 9, 1, 1, 1)
        self.serviceCompanyLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.serviceCompanyLabel.setObjectName(_fromUtf8("serviceCompanyLabel"))
        self.gridLayout_3.addWidget(self.serviceCompanyLabel, 9, 3, 1, 1)
        self.serviceCompanyLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.serviceCompanyLineEdit.setObjectName(_fromUtf8("serviceCompanyLineEdit"))
        self.gridLayout_3.addWidget(self.serviceCompanyLineEdit, 9, 5, 1, 1)
        self.serviceDateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.serviceDateLabel.setObjectName(_fromUtf8("serviceDateLabel"))
        self.gridLayout_3.addWidget(self.serviceDateLabel, 10, 0, 1, 1)
        self.serviceDateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.serviceDateLineEdit.setObjectName(_fromUtf8("serviceDateLineEdit"))
        self.gridLayout_3.addWidget(self.serviceDateLineEdit, 10, 1, 1, 1)
        self.depthTypeLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.depthTypeLineEdit.setObjectName(_fromUtf8("depthTypeLineEdit"))
        self.gridLayout_3.addWidget(self.depthTypeLineEdit, 13, 1, 1, 1)
        self.depthTypeLabel_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.depthTypeLabel_2.setObjectName(_fromUtf8("depthTypeLabel_2"))
        self.gridLayout_3.addWidget(self.depthTypeLabel_2, 13, 0, 1, 1)
        self.tdLoggerLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tdLoggerLineEdit.setObjectName(_fromUtf8("tdLoggerLineEdit"))
        self.gridLayout_3.addWidget(self.tdLoggerLineEdit, 11, 1, 1, 1)
        self.tdLoggerUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tdLoggerUnitLabel.setObjectName(_fromUtf8("tdLoggerUnitLabel"))
        self.gridLayout_3.addWidget(self.tdLoggerUnitLabel, 11, 3, 1, 1)
        self.defaultRwUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.defaultRwUnitComboBox.setObjectName(_fromUtf8("defaultRwUnitComboBox"))
        self.gridLayout_3.addWidget(self.defaultRwUnitComboBox, 1, 5, 1, 1)
        self.defaultRwtComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.defaultRwtComboBox.setObjectName(_fromUtf8("defaultRwtComboBox"))
        self.gridLayout_3.addWidget(self.defaultRwtComboBox, 2, 5, 1, 1)
        self.logStartUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.logStartUnitComboBox.setObjectName(_fromUtf8("logStartUnitComboBox"))
        self.gridLayout_3.addWidget(self.logStartUnitComboBox, 3, 5, 1, 1)
        self.logStepUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.logStepUnitComboBox.setObjectName(_fromUtf8("logStepUnitComboBox"))
        self.gridLayout_3.addWidget(self.logStepUnitComboBox, 4, 5, 1, 1)
        self.logStopUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.logStopUnitComboBox.setObjectName(_fromUtf8("logStopUnitComboBox"))
        self.gridLayout_3.addWidget(self.logStopUnitComboBox, 6, 5, 1, 1)
        self.typeOfFluidInHoleLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.typeOfFluidInHoleLineEdit.setObjectName(_fromUtf8("typeOfFluidInHoleLineEdit"))
        self.gridLayout_3.addWidget(self.typeOfFluidInHoleLineEdit, 12, 5, 1, 1)
        self.typeOfFluidInHoleLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.typeOfFluidInHoleLabel.setObjectName(_fromUtf8("typeOfFluidInHoleLabel"))
        self.gridLayout_3.addWidget(self.typeOfFluidInHoleLabel, 12, 3, 1, 1)
        self.totalSamplesLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.totalSamplesLineEdit.setObjectName(_fromUtf8("totalSamplesLineEdit"))
        self.gridLayout_3.addWidget(self.totalSamplesLineEdit, 12, 1, 1, 1)
        self.totalSamplesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.totalSamplesLabel.setObjectName(_fromUtf8("totalSamplesLabel"))
        self.gridLayout_3.addWidget(self.totalSamplesLabel, 12, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.lowerGroupbox = QtGui.QGroupBox(LogServiceLasWizardPage)
        self.lowerGroupbox.setTitle(_fromUtf8(""))
        self.lowerGroupbox.setObjectName(_fromUtf8("lowerGroupbox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.lowerGroupbox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.viewfilePushButton = QtGui.QPushButton(self.lowerGroupbox)
        self.viewfilePushButton.setObjectName(_fromUtf8("viewfilePushButton"))
        self.horizontalLayout_2.addWidget(self.viewfilePushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.lowerGroupbox)

        self.retranslateUi(LogServiceLasWizardPage)
        QtCore.QMetaObject.connectSlotsByName(LogServiceLasWizardPage)

    def retranslateUi(self, LogServiceLasWizardPage):
        LogServiceLasWizardPage.setWindowTitle(_translate("LogServiceLasWizardPage", "Log service details", None))
        self.newLogSetRadioButton.setText(_translate("LogServiceLasWizardPage", "New log set", None))
        self.existingLogSetRadioButton.setText(_translate("LogServiceLasWizardPage", "Existing log set", None))
        self.logStepLabel.setText(_translate("LogServiceLasWizardPage", "Log step", None))
        self.defaultRwLabel.setText(_translate("LogServiceLasWizardPage", "Default Rw", None))
        self.defaultRwUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.analysisByLabel.setText(_translate("LogServiceLasWizardPage", "Analysis by", None))
        self.defaultRwtLabel.setText(_translate("LogServiceLasWizardPage", "Default Rwt", None))
        self.defaultRwtUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.analysisLocationLabel.setText(_translate("LogServiceLasWizardPage", "Analysis location", None))
        self.tdLoggerLabel.setText(_translate("LogServiceLasWizardPage", "TD logger", None))
        self.logStartUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.logStartLabel.setText(_translate("LogServiceLasWizardPage", "Log start", None))
        self.loggingReferenceLabel.setText(_translate("LogServiceLasWizardPage", "Logging reference", None))
        self.logStepUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.runNumberLabel.setText(_translate("LogServiceLasWizardPage", "Run number", None))
        self.logStopLabel.setText(_translate("LogServiceLasWizardPage", "Log stop", None))
        self.logStopUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.depthDomainLabel.setText(_translate("LogServiceLasWizardPage", "Depth domain", None))
        self.nullValueLabel.setText(_translate("LogServiceLasWizardPage", "Null value", None))
        self.serviceCompanyLabel.setText(_translate("LogServiceLasWizardPage", "Service company", None))
        self.serviceDateLabel.setText(_translate("LogServiceLasWizardPage", "Service date", None))
        self.depthTypeLabel_2.setText(_translate("LogServiceLasWizardPage", "Depth type", None))
        self.tdLoggerUnitLabel.setText(_translate("LogServiceLasWizardPage", "Unit", None))
        self.typeOfFluidInHoleLabel.setText(_translate("LogServiceLasWizardPage", "Type of fluid in hole", None))
        self.totalSamplesLabel.setText(_translate("LogServiceLasWizardPage", "Total samples", None))
        self.viewfilePushButton.setText(_translate("LogServiceLasWizardPage", "View file ", None))

