# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welllaswizardpage.ui'
#
# Created: Wed Dec 31 08:15:22 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WellLasWizardPage(object):
    def setupUi(self, WellLasWizardPage):
        WellLasWizardPage.setObjectName(_fromUtf8("WellLasWizardPage"))
        WellLasWizardPage.resize(579, 831)
        self.verticalLayout = QtGui.QVBoxLayout(WellLasWizardPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.upperGroupBox = QtGui.QGroupBox(WellLasWizardPage)
        self.upperGroupBox.setTitle(_fromUtf8(""))
        self.upperGroupBox.setObjectName(_fromUtf8("upperGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.upperGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newWellRadioButton = QtGui.QRadioButton(self.upperGroupBox)
        self.newWellRadioButton.setObjectName(_fromUtf8("newWellRadioButton"))
        self.horizontalLayout.addWidget(self.newWellRadioButton)
        self.existingWellRadioButton = QtGui.QRadioButton(self.upperGroupBox)
        self.existingWellRadioButton.setObjectName(_fromUtf8("existingWellRadioButton"))
        self.horizontalLayout.addWidget(self.existingWellRadioButton)
        self.existingWellComboBox = QtGui.QComboBox(self.upperGroupBox)
        self.existingWellComboBox.setObjectName(_fromUtf8("existingWellComboBox"))
        self.horizontalLayout.addWidget(self.existingWellComboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.upperGroupBox)
        self.requiredGroupBox = QtGui.QGroupBox(WellLasWizardPage)
        self.requiredGroupBox.setTitle(_fromUtf8(""))
        self.requiredGroupBox.setObjectName(_fromUtf8("requiredGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.requiredGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.depthTypeComboBox = QtGui.QComboBox(self.requiredGroupBox)
        self.depthTypeComboBox.setObjectName(_fromUtf8("depthTypeComboBox"))
        self.gridLayout_2.addWidget(self.depthTypeComboBox, 1, 2, 1, 1)
        self.elevationOfDepthReferenceLineEdit = QtGui.QLineEdit(self.requiredGroupBox)
        self.elevationOfDepthReferenceLineEdit.setObjectName(_fromUtf8("elevationOfDepthReferenceLineEdit"))
        self.gridLayout_2.addWidget(self.elevationOfDepthReferenceLineEdit, 3, 2, 1, 1)
        self.elevationOfDepthReferenceLabel = QtGui.QLabel(self.requiredGroupBox)
        self.elevationOfDepthReferenceLabel.setObjectName(_fromUtf8("elevationOfDepthReferenceLabel"))
        self.gridLayout_2.addWidget(self.elevationOfDepthReferenceLabel, 3, 0, 1, 1)
        self.wellNameLabel = QtGui.QLabel(self.requiredGroupBox)
        self.wellNameLabel.setObjectName(_fromUtf8("wellNameLabel"))
        self.gridLayout_2.addWidget(self.wellNameLabel, 0, 0, 1, 2)
        self.wellNameLineEdit = QtGui.QLineEdit(self.requiredGroupBox)
        self.wellNameLineEdit.setObjectName(_fromUtf8("wellNameLineEdit"))
        self.gridLayout_2.addWidget(self.wellNameLineEdit, 0, 2, 1, 1)
        self.depthTypeLabel = QtGui.QLabel(self.requiredGroupBox)
        self.depthTypeLabel.setObjectName(_fromUtf8("depthTypeLabel"))
        self.gridLayout_2.addWidget(self.depthTypeLabel, 1, 0, 1, 1)
        self.depthReferenceLabel = QtGui.QLabel(self.requiredGroupBox)
        self.depthReferenceLabel.setObjectName(_fromUtf8("depthReferenceLabel"))
        self.gridLayout_2.addWidget(self.depthReferenceLabel, 2, 0, 1, 2)
        self.depthReferenceComboBox = QtGui.QComboBox(self.requiredGroupBox)
        self.depthReferenceComboBox.setObjectName(_fromUtf8("depthReferenceComboBox"))
        self.gridLayout_2.addWidget(self.depthReferenceComboBox, 2, 2, 1, 1)
        self.depthReferenceUnitLabel = QtGui.QLabel(self.requiredGroupBox)
        self.depthReferenceUnitLabel.setObjectName(_fromUtf8("depthReferenceUnitLabel"))
        self.gridLayout_2.addWidget(self.depthReferenceUnitLabel, 2, 3, 1, 1)
        self.depthReferenceUnitComboBox = QtGui.QComboBox(self.requiredGroupBox)
        self.depthReferenceUnitComboBox.setObjectName(_fromUtf8("depthReferenceUnitComboBox"))
        self.gridLayout_2.addWidget(self.depthReferenceUnitComboBox, 2, 4, 1, 1)
        self.elevationOfDepthReferenceUnitLabel = QtGui.QLabel(self.requiredGroupBox)
        self.elevationOfDepthReferenceUnitLabel.setObjectName(_fromUtf8("elevationOfDepthReferenceUnitLabel"))
        self.gridLayout_2.addWidget(self.elevationOfDepthReferenceUnitLabel, 3, 3, 1, 1)
        self.elevationOfDepthReferenceUnitComboBox = QtGui.QComboBox(self.requiredGroupBox)
        self.elevationOfDepthReferenceUnitComboBox.setObjectName(_fromUtf8("elevationOfDepthReferenceUnitComboBox"))
        self.gridLayout_2.addWidget(self.elevationOfDepthReferenceUnitComboBox, 3, 4, 1, 1)
        self.importOnlyRequiredDataRadioButton = QtGui.QRadioButton(self.requiredGroupBox)
        self.importOnlyRequiredDataRadioButton.setObjectName(_fromUtf8("importOnlyRequiredDataRadioButton"))
        self.gridLayout_2.addWidget(self.importOnlyRequiredDataRadioButton, 4, 0, 1, 1)
        self.depthTypeUnitLabel = QtGui.QLabel(self.requiredGroupBox)
        self.depthTypeUnitLabel.setObjectName(_fromUtf8("depthTypeUnitLabel"))
        self.gridLayout_2.addWidget(self.depthTypeUnitLabel, 1, 3, 1, 1)
        self.depthTypeUnitComboBox = QtGui.QComboBox(self.requiredGroupBox)
        self.depthTypeUnitComboBox.setObjectName(_fromUtf8("depthTypeUnitComboBox"))
        self.gridLayout_2.addWidget(self.depthTypeUnitComboBox, 1, 4, 1, 1)
        self.importAllDataRadioButton = QtGui.QRadioButton(self.requiredGroupBox)
        self.importAllDataRadioButton.setObjectName(_fromUtf8("importAllDataRadioButton"))
        self.gridLayout_2.addWidget(self.importAllDataRadioButton, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.requiredGroupBox)
        self.scrollArea = QtGui.QScrollArea(WellLasWizardPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 565, 589))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.waterDepthUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.waterDepthUnitComboBox.setObjectName(_fromUtf8("waterDepthUnitComboBox"))
        self.gridLayout_3.addWidget(self.waterDepthUnitComboBox, 12, 6, 1, 1)
        self.licenseLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.licenseLabel.setObjectName(_fromUtf8("licenseLabel"))
        self.gridLayout_3.addWidget(self.licenseLabel, 4, 0, 1, 1)
        self.glElevationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.glElevationLabel.setObjectName(_fromUtf8("glElevationLabel"))
        self.gridLayout_3.addWidget(self.glElevationLabel, 17, 0, 1, 1)
        self.waterDepthLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.waterDepthLabel.setObjectName(_fromUtf8("waterDepthLabel"))
        self.gridLayout_3.addWidget(self.waterDepthLabel, 12, 0, 1, 1)
        self.waterDepthUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.waterDepthUnitLabel.setObjectName(_fromUtf8("waterDepthUnitLabel"))
        self.gridLayout_3.addWidget(self.waterDepthUnitLabel, 12, 3, 1, 1)
        self.glElevationUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.glElevationUnitLabel.setObjectName(_fromUtf8("glElevationUnitLabel"))
        self.gridLayout_3.addWidget(self.glElevationUnitLabel, 17, 3, 1, 1)
        self.drillingReferenceComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.drillingReferenceComboBox.setObjectName(_fromUtf8("drillingReferenceComboBox"))
        self.gridLayout_3.addWidget(self.drillingReferenceComboBox, 14, 1, 1, 1)
        self.areaLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.areaLineEdit.setObjectName(_fromUtf8("areaLineEdit"))
        self.gridLayout_3.addWidget(self.areaLineEdit, 0, 1, 1, 2)
        self.blockLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.blockLabel.setObjectName(_fromUtf8("blockLabel"))
        self.gridLayout_3.addWidget(self.blockLabel, 1, 0, 1, 1)
        self.apiLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.apiLineEdit.setObjectName(_fromUtf8("apiLineEdit"))
        self.gridLayout_3.addWidget(self.apiLineEdit, 0, 5, 1, 3)
        self.blockLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.blockLineEdit.setObjectName(_fromUtf8("blockLineEdit"))
        self.gridLayout_3.addWidget(self.blockLineEdit, 1, 1, 1, 2)
        self.companyLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.companyLabel.setObjectName(_fromUtf8("companyLabel"))
        self.gridLayout_3.addWidget(self.companyLabel, 1, 3, 1, 1)
        self.companyLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.companyLineEdit.setObjectName(_fromUtf8("companyLineEdit"))
        self.gridLayout_3.addWidget(self.companyLineEdit, 1, 5, 1, 3)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 8, 0, 1, 4)
        self.areaLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.areaLabel.setObjectName(_fromUtf8("areaLabel"))
        self.gridLayout_3.addWidget(self.areaLabel, 0, 0, 1, 1)
        self.completionStatusLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.completionStatusLabel.setObjectName(_fromUtf8("completionStatusLabel"))
        self.gridLayout_3.addWidget(self.completionStatusLabel, 2, 0, 1, 1)
        self.completionStatusLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.completionStatusLineEdit.setObjectName(_fromUtf8("completionStatusLineEdit"))
        self.gridLayout_3.addWidget(self.completionStatusLineEdit, 2, 1, 1, 1)
        self.countryLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.countryLabel.setObjectName(_fromUtf8("countryLabel"))
        self.gridLayout_3.addWidget(self.countryLabel, 2, 3, 1, 1)
        self.countryLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.countryLineEdit.setObjectName(_fromUtf8("countryLineEdit"))
        self.gridLayout_3.addWidget(self.countryLineEdit, 2, 6, 1, 1)
        self.apiLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.apiLabel.setObjectName(_fromUtf8("apiLabel"))
        self.gridLayout_3.addWidget(self.apiLabel, 0, 3, 1, 1)
        self.countyLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.countyLineEdit.setObjectName(_fromUtf8("countyLineEdit"))
        self.gridLayout_3.addWidget(self.countyLineEdit, 3, 1, 1, 1)
        self.fieldLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.fieldLabel.setObjectName(_fromUtf8("fieldLabel"))
        self.gridLayout_3.addWidget(self.fieldLabel, 3, 3, 1, 1)
        self.countyLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.countyLabel.setObjectName(_fromUtf8("countyLabel"))
        self.gridLayout_3.addWidget(self.countyLabel, 3, 0, 1, 1)
        self.fieldLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.fieldLineEdit.setObjectName(_fromUtf8("fieldLineEdit"))
        self.gridLayout_3.addWidget(self.fieldLineEdit, 3, 6, 1, 1)
        self.drillingContractorLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drillingContractorLabel.setObjectName(_fromUtf8("drillingContractorLabel"))
        self.gridLayout_3.addWidget(self.drillingContractorLabel, 9, 0, 1, 1)
        self.locationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.gridLayout_3.addWidget(self.locationLabel, 4, 3, 1, 1)
        self.licenseLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.licenseLineEdit.setObjectName(_fromUtf8("licenseLineEdit"))
        self.gridLayout_3.addWidget(self.licenseLineEdit, 4, 1, 1, 1)
        self.waterDepthLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.waterDepthLineEdit.setObjectName(_fromUtf8("waterDepthLineEdit"))
        self.gridLayout_3.addWidget(self.waterDepthLineEdit, 12, 1, 1, 1)
        self.rigNameLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.rigNameLineEdit.setObjectName(_fromUtf8("rigNameLineEdit"))
        self.gridLayout_3.addWidget(self.rigNameLineEdit, 9, 6, 1, 1)
        self.spudDateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.spudDateLabel.setObjectName(_fromUtf8("spudDateLabel"))
        self.gridLayout_3.addWidget(self.spudDateLabel, 10, 0, 1, 1)
        self.dfElevationUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.dfElevationUnitComboBox.setObjectName(_fromUtf8("dfElevationUnitComboBox"))
        self.gridLayout_3.addWidget(self.dfElevationUnitComboBox, 15, 6, 1, 1)
        self.provinceLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.provinceLineEdit.setObjectName(_fromUtf8("provinceLineEdit"))
        self.gridLayout_3.addWidget(self.provinceLineEdit, 6, 6, 1, 1)
        self.locationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.locationLineEdit.setObjectName(_fromUtf8("locationLineEdit"))
        self.gridLayout_3.addWidget(self.locationLineEdit, 4, 6, 1, 1)
        self.operatorLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.operatorLabel.setObjectName(_fromUtf8("operatorLabel"))
        self.gridLayout_3.addWidget(self.operatorLabel, 6, 0, 1, 1)
        self.provinceLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.provinceLabel.setObjectName(_fromUtf8("provinceLabel"))
        self.gridLayout_3.addWidget(self.provinceLabel, 6, 3, 1, 1)
        self.operatorLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.operatorLineEdit.setObjectName(_fromUtf8("operatorLineEdit"))
        self.gridLayout_3.addWidget(self.operatorLineEdit, 6, 1, 1, 1)
        self.dfElevationUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.dfElevationUnitLabel.setObjectName(_fromUtf8("dfElevationUnitLabel"))
        self.gridLayout_3.addWidget(self.dfElevationUnitLabel, 15, 3, 1, 1)
        self.drillingContractorLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.drillingContractorLineEdit.setObjectName(_fromUtf8("drillingContractorLineEdit"))
        self.gridLayout_3.addWidget(self.drillingContractorLineEdit, 9, 1, 1, 1)
        self.stateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.gridLayout_3.addWidget(self.stateLabel, 7, 0, 1, 1)
        self.stateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.stateLineEdit.setObjectName(_fromUtf8("stateLineEdit"))
        self.gridLayout_3.addWidget(self.stateLineEdit, 7, 1, 1, 1)
        self.elevationAbovePDLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.elevationAbovePDLabel.setObjectName(_fromUtf8("elevationAbovePDLabel"))
        self.gridLayout_3.addWidget(self.elevationAbovePDLabel, 20, 0, 1, 1)
        self.geodeticDatumLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.geodeticDatumLabel.setObjectName(_fromUtf8("geodeticDatumLabel"))
        self.gridLayout_3.addWidget(self.geodeticDatumLabel, 18, 0, 1, 1)
        self.rigNameLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.rigNameLabel.setObjectName(_fromUtf8("rigNameLabel"))
        self.gridLayout_3.addWidget(self.rigNameLabel, 9, 3, 1, 1)
        self.spudDateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.spudDateLineEdit.setObjectName(_fromUtf8("spudDateLineEdit"))
        self.gridLayout_3.addWidget(self.spudDateLineEdit, 10, 1, 1, 1)
        self.tdDateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tdDateLabel.setObjectName(_fromUtf8("tdDateLabel"))
        self.gridLayout_3.addWidget(self.tdDateLabel, 10, 3, 1, 1)
        self.drillingReserenceLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.drillingReserenceLabel.setObjectName(_fromUtf8("drillingReserenceLabel"))
        self.gridLayout_3.addWidget(self.drillingReserenceLabel, 14, 0, 1, 1)
        self.tdDateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tdDateLineEdit.setObjectName(_fromUtf8("tdDateLineEdit"))
        self.gridLayout_3.addWidget(self.tdDateLineEdit, 10, 6, 1, 1)
        self.tdDrillerLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tdDrillerLabel.setObjectName(_fromUtf8("tdDrillerLabel"))
        self.gridLayout_3.addWidget(self.tdDrillerLabel, 11, 0, 1, 1)
        self.tdDrillerUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.tdDrillerUnitLabel.setObjectName(_fromUtf8("tdDrillerUnitLabel"))
        self.gridLayout_3.addWidget(self.tdDrillerUnitLabel, 11, 3, 1, 1)
        self.glElevationComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.glElevationComboBox.setObjectName(_fromUtf8("glElevationComboBox"))
        self.gridLayout_3.addWidget(self.glElevationComboBox, 17, 6, 1, 1)
        self.uwiLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.uwiLabel.setObjectName(_fromUtf8("uwiLabel"))
        self.gridLayout_3.addWidget(self.uwiLabel, 7, 3, 1, 1)
        self.tdDrillerLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.tdDrillerLineEdit.setObjectName(_fromUtf8("tdDrillerLineEdit"))
        self.gridLayout_3.addWidget(self.tdDrillerLineEdit, 11, 1, 1, 1)
        self.tdDrillerUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.tdDrillerUnitComboBox.setObjectName(_fromUtf8("tdDrillerUnitComboBox"))
        self.gridLayout_3.addWidget(self.tdDrillerUnitComboBox, 11, 6, 1, 1)
        self.kbElevationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.kbElevationLabel.setObjectName(_fromUtf8("kbElevationLabel"))
        self.gridLayout_3.addWidget(self.kbElevationLabel, 16, 0, 1, 1)
        self.kbElevationUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.kbElevationUnitLabel.setObjectName(_fromUtf8("kbElevationUnitLabel"))
        self.gridLayout_3.addWidget(self.kbElevationUnitLabel, 16, 3, 1, 1)
        self.uwiLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uwiLineEdit.setObjectName(_fromUtf8("uwiLineEdit"))
        self.gridLayout_3.addWidget(self.uwiLineEdit, 7, 6, 1, 1)
        self.dfElevationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.dfElevationLineEdit.setObjectName(_fromUtf8("dfElevationLineEdit"))
        self.gridLayout_3.addWidget(self.dfElevationLineEdit, 15, 1, 1, 1)
        self.dfElevationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.dfElevationLabel.setObjectName(_fromUtf8("dfElevationLabel"))
        self.gridLayout_3.addWidget(self.dfElevationLabel, 15, 0, 1, 1)
        self.permanentDatumElevationUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.permanentDatumElevationUnitLabel.setObjectName(_fromUtf8("permanentDatumElevationUnitLabel"))
        self.gridLayout_3.addWidget(self.permanentDatumElevationUnitLabel, 19, 3, 1, 1)
        self.permanentDatumLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.permanentDatumLineEdit.setObjectName(_fromUtf8("permanentDatumLineEdit"))
        self.gridLayout_3.addWidget(self.permanentDatumLineEdit, 18, 6, 1, 1)
        self.permanentDatumLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.permanentDatumLabel.setObjectName(_fromUtf8("permanentDatumLabel"))
        self.gridLayout_3.addWidget(self.permanentDatumLabel, 18, 3, 1, 1)
        self.kbElevationUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.kbElevationUnitComboBox.setObjectName(_fromUtf8("kbElevationUnitComboBox"))
        self.gridLayout_3.addWidget(self.kbElevationUnitComboBox, 16, 6, 1, 1)
        self.kbElevationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.kbElevationLineEdit.setObjectName(_fromUtf8("kbElevationLineEdit"))
        self.gridLayout_3.addWidget(self.kbElevationLineEdit, 16, 1, 1, 1)
        self.glElevationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.glElevationLineEdit.setObjectName(_fromUtf8("glElevationLineEdit"))
        self.gridLayout_3.addWidget(self.glElevationLineEdit, 17, 1, 1, 1)
        self.geodeticDatumLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.geodeticDatumLineEdit.setObjectName(_fromUtf8("geodeticDatumLineEdit"))
        self.gridLayout_3.addWidget(self.geodeticDatumLineEdit, 18, 1, 1, 1)
        self.permanentDatumElevationLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.permanentDatumElevationLineEdit.setObjectName(_fromUtf8("permanentDatumElevationLineEdit"))
        self.gridLayout_3.addWidget(self.permanentDatumElevationLineEdit, 19, 1, 1, 1)
        self.permanentDatumElevationLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.permanentDatumElevationLabel.setObjectName(_fromUtf8("permanentDatumElevationLabel"))
        self.gridLayout_3.addWidget(self.permanentDatumElevationLabel, 19, 0, 1, 1)
        self.elevationAbovePDComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.elevationAbovePDComboBox.setObjectName(_fromUtf8("elevationAbovePDComboBox"))
        self.gridLayout_3.addWidget(self.elevationAbovePDComboBox, 20, 6, 1, 1)
        self.elevationAbovePDUnitLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.elevationAbovePDUnitLabel.setObjectName(_fromUtf8("elevationAbovePDUnitLabel"))
        self.gridLayout_3.addWidget(self.elevationAbovePDUnitLabel, 20, 3, 1, 1)
        self.utmZoneLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.utmZoneLabel.setObjectName(_fromUtf8("utmZoneLabel"))
        self.gridLayout_3.addWidget(self.utmZoneLabel, 22, 0, 1, 1)
        self.latitudeLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.latitudeLineEdit.setObjectName(_fromUtf8("latitudeLineEdit"))
        self.gridLayout_3.addWidget(self.latitudeLineEdit, 21, 1, 1, 1)
        self.longitudeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.gridLayout_3.addWidget(self.longitudeLabel, 21, 3, 1, 1)
        self.longitudeLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.longitudeLineEdit.setObjectName(_fromUtf8("longitudeLineEdit"))
        self.gridLayout_3.addWidget(self.longitudeLineEdit, 21, 6, 1, 1)
        self.utmZoneLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.utmZoneLineEdit.setObjectName(_fromUtf8("utmZoneLineEdit"))
        self.gridLayout_3.addWidget(self.utmZoneLineEdit, 22, 1, 1, 1)
        self.horizontalCoordinateSystemLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.horizontalCoordinateSystemLabel.setObjectName(_fromUtf8("horizontalCoordinateSystemLabel"))
        self.gridLayout_3.addWidget(self.horizontalCoordinateSystemLabel, 22, 3, 1, 1)
        self.horizontalCoordinateSystemLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.horizontalCoordinateSystemLineEdit.setObjectName(_fromUtf8("horizontalCoordinateSystemLineEdit"))
        self.gridLayout_3.addWidget(self.horizontalCoordinateSystemLineEdit, 22, 6, 1, 1)
        self.latitudeLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.gridLayout_3.addWidget(self.latitudeLabel, 21, 0, 1, 1)
        self.elevationAbovePDLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.elevationAbovePDLineEdit.setObjectName(_fromUtf8("elevationAbovePDLineEdit"))
        self.gridLayout_3.addWidget(self.elevationAbovePDLineEdit, 20, 1, 1, 1)
        self.xCoordinateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.xCoordinateLabel.setObjectName(_fromUtf8("xCoordinateLabel"))
        self.gridLayout_3.addWidget(self.xCoordinateLabel, 23, 0, 1, 1)
        self.xCoordinateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.xCoordinateLineEdit.setObjectName(_fromUtf8("xCoordinateLineEdit"))
        self.gridLayout_3.addWidget(self.xCoordinateLineEdit, 23, 1, 1, 1)
        self.yCoordinateLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.yCoordinateLabel.setObjectName(_fromUtf8("yCoordinateLabel"))
        self.gridLayout_3.addWidget(self.yCoordinateLabel, 23, 3, 1, 1)
        self.yCoordinateLineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.yCoordinateLineEdit.setObjectName(_fromUtf8("yCoordinateLineEdit"))
        self.gridLayout_3.addWidget(self.yCoordinateLineEdit, 23, 6, 1, 1)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 13, 0, 1, 5)
        self.permDatumElevUnitComboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.permDatumElevUnitComboBox.setObjectName(_fromUtf8("permDatumElevUnitComboBox"))
        self.gridLayout_3.addWidget(self.permDatumElevUnitComboBox, 19, 6, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.lowerGroupbox = QtGui.QGroupBox(WellLasWizardPage)
        self.lowerGroupbox.setTitle(_fromUtf8(""))
        self.lowerGroupbox.setObjectName(_fromUtf8("lowerGroupbox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.lowerGroupbox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.viewfilePushButton = QtGui.QPushButton(self.lowerGroupbox)
        self.viewfilePushButton.setObjectName(_fromUtf8("viewfilePushButton"))
        self.horizontalLayout_2.addWidget(self.viewfilePushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.lowerGroupbox)

        self.retranslateUi(WellLasWizardPage)
        QtCore.QMetaObject.connectSlotsByName(WellLasWizardPage)

    def retranslateUi(self, WellLasWizardPage):
        WellLasWizardPage.setWindowTitle(_translate("WellLasWizardPage", "Well details", None))
        self.newWellRadioButton.setText(_translate("WellLasWizardPage", "New well", None))
        self.existingWellRadioButton.setText(_translate("WellLasWizardPage", "Existing well", None))
        self.elevationOfDepthReferenceLabel.setText(_translate("WellLasWizardPage", "Elevation of depth reference", None))
        self.wellNameLabel.setText(_translate("WellLasWizardPage", "Well name", None))
        self.depthTypeLabel.setText(_translate("WellLasWizardPage", "Depth type", None))
        self.depthReferenceLabel.setText(_translate("WellLasWizardPage", "Depth reference", None))
        self.depthReferenceUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.elevationOfDepthReferenceUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.importOnlyRequiredDataRadioButton.setText(_translate("WellLasWizardPage", "Import only required data", None))
        self.depthTypeUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.importAllDataRadioButton.setText(_translate("WellLasWizardPage", "Import all header and parameter data", None))
        self.licenseLabel.setText(_translate("WellLasWizardPage", "License", None))
        self.glElevationLabel.setText(_translate("WellLasWizardPage", "GL elevation", None))
        self.waterDepthLabel.setText(_translate("WellLasWizardPage", "Water depth", None))
        self.waterDepthUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.glElevationUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.blockLabel.setText(_translate("WellLasWizardPage", "Block", None))
        self.companyLabel.setText(_translate("WellLasWizardPage", "Company", None))
        self.areaLabel.setText(_translate("WellLasWizardPage", "Area", None))
        self.completionStatusLabel.setText(_translate("WellLasWizardPage", "Completion status", None))
        self.countryLabel.setText(_translate("WellLasWizardPage", "Country", None))
        self.apiLabel.setText(_translate("WellLasWizardPage", "API", None))
        self.fieldLabel.setText(_translate("WellLasWizardPage", "Field", None))
        self.countyLabel.setText(_translate("WellLasWizardPage", "County", None))
        self.drillingContractorLabel.setText(_translate("WellLasWizardPage", "Drilling contractor", None))
        self.locationLabel.setText(_translate("WellLasWizardPage", "Location", None))
        self.spudDateLabel.setText(_translate("WellLasWizardPage", "Spud date", None))
        self.operatorLabel.setText(_translate("WellLasWizardPage", "Operator", None))
        self.provinceLabel.setText(_translate("WellLasWizardPage", "Province", None))
        self.dfElevationUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.stateLabel.setText(_translate("WellLasWizardPage", "State", None))
        self.elevationAbovePDLabel.setToolTip(_translate("WellLasWizardPage", "Elevation above permanent datum", None))
        self.elevationAbovePDLabel.setText(_translate("WellLasWizardPage", "Elevation above PD", None))
        self.geodeticDatumLabel.setText(_translate("WellLasWizardPage", "Geodetic datum", None))
        self.rigNameLabel.setText(_translate("WellLasWizardPage", "Rig name", None))
        self.tdDateLabel.setText(_translate("WellLasWizardPage", "TD date", None))
        self.drillingReserenceLabel.setText(_translate("WellLasWizardPage", "Drilling reference", None))
        self.tdDrillerLabel.setText(_translate("WellLasWizardPage", "TD driller", None))
        self.tdDrillerUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.uwiLabel.setText(_translate("WellLasWizardPage", "UWI", None))
        self.kbElevationLabel.setText(_translate("WellLasWizardPage", "KB elevation", None))
        self.kbElevationUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.dfElevationLabel.setText(_translate("WellLasWizardPage", "DF elevation", None))
        self.permanentDatumElevationUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.permanentDatumLabel.setText(_translate("WellLasWizardPage", "Permanent datum", None))
        self.permanentDatumElevationLabel.setText(_translate("WellLasWizardPage", "Permanent datum elevation", None))
        self.elevationAbovePDUnitLabel.setText(_translate("WellLasWizardPage", "Unit", None))
        self.utmZoneLabel.setText(_translate("WellLasWizardPage", "UTM zone", None))
        self.longitudeLabel.setText(_translate("WellLasWizardPage", "Longitude", None))
        self.horizontalCoordinateSystemLabel.setText(_translate("WellLasWizardPage", "Horizontal coordinate system", None))
        self.latitudeLabel.setText(_translate("WellLasWizardPage", "Latitude", None))
        self.xCoordinateLabel.setText(_translate("WellLasWizardPage", "X coordinate", None))
        self.yCoordinateLabel.setText(_translate("WellLasWizardPage", "Y coordinate", None))
        self.viewfilePushButton.setText(_translate("WellLasWizardPage", "View file ", None))

