# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created: Mon Jun  1 15:29:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(747, 534)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dataSelectionTab = QtGui.QWidget()
        self.dataSelectionTab.setObjectName(_fromUtf8("dataSelectionTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dataSelectionTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.dataSelectionTab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 717, 322))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkTabVerticalLayout = QtGui.QVBoxLayout()
        self.checkTabVerticalLayout.setObjectName(_fromUtf8("checkTabVerticalLayout"))
        self.checkTabTableLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.checkTabTableLabel.setObjectName(_fromUtf8("checkTabTableLabel"))
        self.checkTabVerticalLayout.addWidget(self.checkTabTableLabel)
        self.chkboxTableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.chkboxTableWidget.setObjectName(_fromUtf8("chkboxTableWidget"))
        self.chkboxTableWidget.setColumnCount(0)
        self.chkboxTableWidget.setRowCount(0)
        self.checkTabVerticalLayout.addWidget(self.chkboxTableWidget)
        self.verticalLayout_4.addLayout(self.checkTabVerticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectionGroupBox = QtGui.QGroupBox(self.dataSelectionTab)
        self.selectionGroupBox.setFlat(False)
        self.selectionGroupBox.setObjectName(_fromUtf8("selectionGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.selectionGroupBox)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.selectDefaultRadioButton = QtGui.QRadioButton(self.selectionGroupBox)
        self.selectDefaultRadioButton.setObjectName(_fromUtf8("selectDefaultRadioButton"))
        self.verticalLayout.addWidget(self.selectDefaultRadioButton)
        self.selectActiveRadioButton = QtGui.QRadioButton(self.selectionGroupBox)
        self.selectActiveRadioButton.setObjectName(_fromUtf8("selectActiveRadioButton"))
        self.verticalLayout.addWidget(self.selectActiveRadioButton)
        self.selectAllRadioButton = QtGui.QRadioButton(self.selectionGroupBox)
        self.selectAllRadioButton.setObjectName(_fromUtf8("selectAllRadioButton"))
        self.verticalLayout.addWidget(self.selectAllRadioButton)
        self.selectNoneRadioButton = QtGui.QRadioButton(self.selectionGroupBox)
        self.selectNoneRadioButton.setObjectName(_fromUtf8("selectNoneRadioButton"))
        self.verticalLayout.addWidget(self.selectNoneRadioButton)
        self.horizontalLayout.addWidget(self.selectionGroupBox)
        self.miscGroupBox = QtGui.QGroupBox(self.dataSelectionTab)
        self.miscGroupBox.setTitle(_fromUtf8(""))
        self.miscGroupBox.setObjectName(_fromUtf8("miscGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.miscGroupBox)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.addTrackPushButton = QtGui.QPushButton(self.miscGroupBox)
        self.addTrackPushButton.setObjectName(_fromUtf8("addTrackPushButton"))
        self.verticalLayout_5.addWidget(self.addTrackPushButton)
        self.horizontalLayout.addWidget(self.miscGroupBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.dataSelectionTab, _fromUtf8(""))
        self.styleTab = QtGui.QWidget()
        self.styleTab.setObjectName(_fromUtf8("styleTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.styleTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.styleTabWidget = QtGui.QTabWidget(self.styleTab)
        self.styleTabWidget.setObjectName(_fromUtf8("styleTabWidget"))
        self.plotStyleTab = QtGui.QWidget()
        self.plotStyleTab.setObjectName(_fromUtf8("plotStyleTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.plotStyleTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.plotScrollArea = QtGui.QScrollArea(self.plotStyleTab)
        self.plotScrollArea.setWidgetResizable(True)
        self.plotScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.plotScrollArea.setObjectName(_fromUtf8("plotScrollArea"))
        self.plotScrollAreaWidgetContents = QtGui.QWidget()
        self.plotScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 686, 497))
        self.plotScrollAreaWidgetContents.setObjectName(_fromUtf8("plotScrollAreaWidgetContents"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.plotScrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.plotStyleGroupBox = QtGui.QGroupBox(self.plotScrollAreaWidgetContents)
        self.plotStyleGroupBox.setObjectName(_fromUtf8("plotStyleGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.plotStyleGroupBox)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plotTitleOnCheckBox = QtGui.QCheckBox(self.plotStyleGroupBox)
        self.plotTitleOnCheckBox.setObjectName(_fromUtf8("plotTitleOnCheckBox"))
        self.gridLayout_3.addWidget(self.plotTitleOnCheckBox, 0, 0, 1, 1)
        self.plotTitleLabel = QtGui.QLabel(self.plotStyleGroupBox)
        self.plotTitleLabel.setObjectName(_fromUtf8("plotTitleLabel"))
        self.gridLayout_3.addWidget(self.plotTitleLabel, 1, 0, 1, 1)
        self.plotTitleLineEdit = QtGui.QLineEdit(self.plotStyleGroupBox)
        self.plotTitleLineEdit.setObjectName(_fromUtf8("plotTitleLineEdit"))
        self.gridLayout_3.addWidget(self.plotTitleLineEdit, 1, 1, 1, 1)
        self.plotDpiLabel = QtGui.QLabel(self.plotStyleGroupBox)
        self.plotDpiLabel.setObjectName(_fromUtf8("plotDpiLabel"))
        self.gridLayout_3.addWidget(self.plotDpiLabel, 2, 0, 1, 1)
        self.plotPrintDPILineEdit = QtGui.QLineEdit(self.plotStyleGroupBox)
        self.plotPrintDPILineEdit.setObjectName(_fromUtf8("plotPrintDPILineEdit"))
        self.gridLayout_3.addWidget(self.plotPrintDPILineEdit, 2, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.plotStyleGroupBox)
        self.trackGroupBox = QtGui.QGroupBox(self.plotScrollAreaWidgetContents)
        self.trackGroupBox.setObjectName(_fromUtf8("trackGroupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.trackGroupBox)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.trackBackgroundOpacitySpinBox = QtGui.QSpinBox(self.trackGroupBox)
        self.trackBackgroundOpacitySpinBox.setObjectName(_fromUtf8("trackBackgroundOpacitySpinBox"))
        self.gridLayout_5.addWidget(self.trackBackgroundOpacitySpinBox, 0, 3, 1, 1)
        self.trackBackgroundOpacityLabel = QtGui.QLabel(self.trackGroupBox)
        self.trackBackgroundOpacityLabel.setObjectName(_fromUtf8("trackBackgroundOpacityLabel"))
        self.gridLayout_5.addWidget(self.trackBackgroundOpacityLabel, 0, 2, 1, 1)
        self.trackBackgroundColorPushButton = QtGui.QPushButton(self.trackGroupBox)
        self.trackBackgroundColorPushButton.setText(_fromUtf8(""))
        self.trackBackgroundColorPushButton.setObjectName(_fromUtf8("trackBackgroundColorPushButton"))
        self.gridLayout_5.addWidget(self.trackBackgroundColorPushButton, 0, 1, 1, 1)
        self.trackBackgroundColorLabel = QtGui.QLabel(self.trackGroupBox)
        self.trackBackgroundColorLabel.setObjectName(_fromUtf8("trackBackgroundColorLabel"))
        self.gridLayout_5.addWidget(self.trackBackgroundColorLabel, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.trackGroupBox)
        self.gridGroupBox = QtGui.QGroupBox(self.plotScrollAreaWidgetContents)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridOnCheckBox = QtGui.QCheckBox(self.gridGroupBox)
        self.gridOnCheckBox.setObjectName(_fromUtf8("gridOnCheckBox"))
        self.gridLayout.addWidget(self.gridOnCheckBox, 0, 0, 1, 1)
        self.gridColorLabel = QtGui.QLabel(self.gridGroupBox)
        self.gridColorLabel.setObjectName(_fromUtf8("gridColorLabel"))
        self.gridLayout.addWidget(self.gridColorLabel, 1, 0, 1, 1)
        self.gridColorPushButton = QtGui.QPushButton(self.gridGroupBox)
        self.gridColorPushButton.setText(_fromUtf8(""))
        self.gridColorPushButton.setObjectName(_fromUtf8("gridColorPushButton"))
        self.gridLayout.addWidget(self.gridColorPushButton, 1, 1, 1, 1)
        self.gridOpacityLabel = QtGui.QLabel(self.gridGroupBox)
        self.gridOpacityLabel.setObjectName(_fromUtf8("gridOpacityLabel"))
        self.gridLayout.addWidget(self.gridOpacityLabel, 2, 0, 1, 1)
        self.gridOpacitySpinBox = QtGui.QSpinBox(self.gridGroupBox)
        self.gridOpacitySpinBox.setObjectName(_fromUtf8("gridOpacitySpinBox"))
        self.gridLayout.addWidget(self.gridOpacitySpinBox, 2, 1, 1, 1)
        self.gridStyleLabel = QtGui.QLabel(self.gridGroupBox)
        self.gridStyleLabel.setObjectName(_fromUtf8("gridStyleLabel"))
        self.gridLayout.addWidget(self.gridStyleLabel, 3, 0, 1, 1)
        self.gridStyleComboBox = QtGui.QComboBox(self.gridGroupBox)
        self.gridStyleComboBox.setObjectName(_fromUtf8("gridStyleComboBox"))
        self.gridLayout.addWidget(self.gridStyleComboBox, 3, 1, 1, 1)
        self.gridVerticalDivLabel = QtGui.QLabel(self.gridGroupBox)
        self.gridVerticalDivLabel.setObjectName(_fromUtf8("gridVerticalDivLabel"))
        self.gridLayout.addWidget(self.gridVerticalDivLabel, 4, 0, 1, 1)
        self.gridVerticalDivSpinBox = QtGui.QSpinBox(self.gridGroupBox)
        self.gridVerticalDivSpinBox.setObjectName(_fromUtf8("gridVerticalDivSpinBox"))
        self.gridLayout.addWidget(self.gridVerticalDivSpinBox, 4, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.gridGroupBox)
        self.labelGroupBox = QtGui.QGroupBox(self.plotScrollAreaWidgetContents)
        self.labelGroupBox.setObjectName(_fromUtf8("labelGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.labelGroupBox)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.labelsExpandedCheckBox = QtGui.QCheckBox(self.labelGroupBox)
        self.labelsExpandedCheckBox.setObjectName(_fromUtf8("labelsExpandedCheckBox"))
        self.gridLayout_4.addWidget(self.labelsExpandedCheckBox, 0, 0, 1, 1)
        self.labelBackgroundColorLabel = QtGui.QLabel(self.labelGroupBox)
        self.labelBackgroundColorLabel.setObjectName(_fromUtf8("labelBackgroundColorLabel"))
        self.gridLayout_4.addWidget(self.labelBackgroundColorLabel, 1, 0, 1, 1)
        self.labelBackgroundColorPushButton = QtGui.QPushButton(self.labelGroupBox)
        self.labelBackgroundColorPushButton.setText(_fromUtf8(""))
        self.labelBackgroundColorPushButton.setObjectName(_fromUtf8("labelBackgroundColorPushButton"))
        self.gridLayout_4.addWidget(self.labelBackgroundColorPushButton, 1, 1, 1, 1)
        self.labelBackgroundOpacityLabel = QtGui.QLabel(self.labelGroupBox)
        self.labelBackgroundOpacityLabel.setObjectName(_fromUtf8("labelBackgroundOpacityLabel"))
        self.gridLayout_4.addWidget(self.labelBackgroundOpacityLabel, 2, 0, 1, 1)
        self.labelBackgroundOpacitySpinBox = QtGui.QSpinBox(self.labelGroupBox)
        self.labelBackgroundOpacitySpinBox.setObjectName(_fromUtf8("labelBackgroundOpacitySpinBox"))
        self.gridLayout_4.addWidget(self.labelBackgroundOpacitySpinBox, 2, 1, 1, 1)
        self.labelForegroundColorLabel = QtGui.QLabel(self.labelGroupBox)
        self.labelForegroundColorLabel.setObjectName(_fromUtf8("labelForegroundColorLabel"))
        self.gridLayout_4.addWidget(self.labelForegroundColorLabel, 3, 0, 1, 1)
        self.labelForegroundColorPushButton = QtGui.QPushButton(self.labelGroupBox)
        self.labelForegroundColorPushButton.setText(_fromUtf8(""))
        self.labelForegroundColorPushButton.setObjectName(_fromUtf8("labelForegroundColorPushButton"))
        self.gridLayout_4.addWidget(self.labelForegroundColorPushButton, 3, 1, 1, 1)
        self.labelForegroundOpacityLabel = QtGui.QLabel(self.labelGroupBox)
        self.labelForegroundOpacityLabel.setObjectName(_fromUtf8("labelForegroundOpacityLabel"))
        self.gridLayout_4.addWidget(self.labelForegroundOpacityLabel, 4, 0, 1, 1)
        self.labelForegroundOpacitySpinBox = QtGui.QSpinBox(self.labelGroupBox)
        self.labelForegroundOpacitySpinBox.setObjectName(_fromUtf8("labelForegroundOpacitySpinBox"))
        self.gridLayout_4.addWidget(self.labelForegroundOpacitySpinBox, 4, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.labelGroupBox)
        self.plotScrollArea.setWidget(self.plotScrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.plotScrollArea)
        self.styleTabWidget.addTab(self.plotStyleTab, _fromUtf8(""))
        self.trackStyleTab = QtGui.QWidget()
        self.trackStyleTab.setObjectName(_fromUtf8("trackStyleTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.trackStyleTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.trackScrollArea = QtGui.QScrollArea(self.trackStyleTab)
        self.trackScrollArea.setWidgetResizable(True)
        self.trackScrollArea.setObjectName(_fromUtf8("trackScrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 701, 301))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.trackTableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.trackTableWidget.setObjectName(_fromUtf8("trackTableWidget"))
        self.trackTableWidget.setColumnCount(0)
        self.trackTableWidget.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.trackTableWidget)
        self.trackScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.trackScrollArea)
        self.trackGroupBox_2 = QtGui.QGroupBox(self.trackStyleTab)
        self.trackGroupBox_2.setObjectName(_fromUtf8("trackGroupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.trackGroupBox_2)
        self.gridLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.trackWidthLabel = QtGui.QLabel(self.trackGroupBox_2)
        self.trackWidthLabel.setObjectName(_fromUtf8("trackWidthLabel"))
        self.gridLayout_7.addWidget(self.trackWidthLabel, 2, 0, 1, 1)
        self.trackGapLabel = QtGui.QLabel(self.trackGroupBox_2)
        self.trackGapLabel.setObjectName(_fromUtf8("trackGapLabel"))
        self.gridLayout_7.addWidget(self.trackGapLabel, 3, 0, 1, 1)
        self.trackWidthLineEdit = QtGui.QLineEdit(self.trackGroupBox_2)
        self.trackWidthLineEdit.setObjectName(_fromUtf8("trackWidthLineEdit"))
        self.gridLayout_7.addWidget(self.trackWidthLineEdit, 2, 2, 1, 1)
        self.trackGapLineEdit = QtGui.QLineEdit(self.trackGroupBox_2)
        self.trackGapLineEdit.setObjectName(_fromUtf8("trackGapLineEdit"))
        self.gridLayout_7.addWidget(self.trackGapLineEdit, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(266, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 2, 1, 1, 1)
        self.trackApplyAllCheckBox = QtGui.QCheckBox(self.trackGroupBox_2)
        self.trackApplyAllCheckBox.setObjectName(_fromUtf8("trackApplyAllCheckBox"))
        self.gridLayout_7.addWidget(self.trackApplyAllCheckBox, 1, 0, 1, 1)
        self.trackGapUnitsComboBox = QtGui.QComboBox(self.trackGroupBox_2)
        self.trackGapUnitsComboBox.setObjectName(_fromUtf8("trackGapUnitsComboBox"))
        self.gridLayout_7.addWidget(self.trackGapUnitsComboBox, 3, 4, 1, 1)
        self.trackWidthUnitsComboBox = QtGui.QComboBox(self.trackGroupBox_2)
        self.trackWidthUnitsComboBox.setObjectName(_fromUtf8("trackWidthUnitsComboBox"))
        self.gridLayout_7.addWidget(self.trackWidthUnitsComboBox, 2, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.trackGroupBox_2)
        self.styleTabWidget.addTab(self.trackStyleTab, _fromUtf8(""))
        self.curveStyleTab = QtGui.QWidget()
        self.curveStyleTab.setObjectName(_fromUtf8("curveStyleTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.curveStyleTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.curveScrollArea = QtGui.QScrollArea(self.curveStyleTab)
        self.curveScrollArea.setWidgetResizable(True)
        self.curveScrollArea.setObjectName(_fromUtf8("curveScrollArea"))
        self.curveAreaWidget = QtGui.QWidget()
        self.curveAreaWidget.setGeometry(QtCore.QRect(0, 0, 701, 415))
        self.curveAreaWidget.setObjectName(_fromUtf8("curveAreaWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.curveAreaWidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.curveTableWidget = QtGui.QTableWidget(self.curveAreaWidget)
        self.curveTableWidget.setObjectName(_fromUtf8("curveTableWidget"))
        self.curveTableWidget.setColumnCount(0)
        self.curveTableWidget.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.curveTableWidget)
        self.curveScrollArea.setWidget(self.curveAreaWidget)
        self.verticalLayout_8.addWidget(self.curveScrollArea)
        self.styleTabWidget.addTab(self.curveStyleTab, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.styleTabWidget)
        self.tabWidget.addTab(self.styleTab, _fromUtf8(""))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dataTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dataScrollArea = QtGui.QScrollArea(self.dataTab)
        self.dataScrollArea.setWidgetResizable(True)
        self.dataScrollArea.setObjectName(_fromUtf8("dataScrollArea"))
        self.dataScrollAreaWidgetContents = QtGui.QWidget()
        self.dataScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 717, 453))
        self.dataScrollAreaWidgetContents.setObjectName(_fromUtf8("dataScrollAreaWidgetContents"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dataScrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dataTableWidget = QtGui.QTableWidget(self.dataScrollAreaWidgetContents)
        self.dataTableWidget.setObjectName(_fromUtf8("dataTableWidget"))
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.dataTableWidget)
        self.dataScrollArea.setWidget(self.dataScrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.dataScrollArea)
        self.tabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.styleTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkTabTableLabel.setText(_translate("Dialog", "Select logs to display in track numbers", None))
        self.selectionGroupBox.setTitle(_translate("Dialog", "Data selection", None))
        self.selectDefaultRadioButton.setToolTip(_translate("Dialog", "Default log types to plot can be set in preferences", None))
        self.selectDefaultRadioButton.setText(_translate("Dialog", "Select default", None))
        self.selectActiveRadioButton.setToolTip(_translate("Dialog", "Plot active logs", None))
        self.selectActiveRadioButton.setText(_translate("Dialog", "Select active", None))
        self.selectAllRadioButton.setText(_translate("Dialog", "Select all", None))
        self.selectNoneRadioButton.setText(_translate("Dialog", "Select none", None))
        self.addTrackPushButton.setText(_translate("Dialog", "Add track", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataSelectionTab), _translate("Dialog", "Data checkboxes", None))
        self.plotStyleGroupBox.setTitle(_translate("Dialog", "Plot", None))
        self.plotTitleOnCheckBox.setText(_translate("Dialog", "Plot title displayed", None))
        self.plotTitleLabel.setText(_translate("Dialog", "Plot title", None))
        self.plotDpiLabel.setText(_translate("Dialog", "Print DPI", None))
        self.trackGroupBox.setTitle(_translate("Dialog", "Track", None))
        self.trackBackgroundOpacityLabel.setText(_translate("Dialog", "Track background opacity", None))
        self.trackBackgroundColorLabel.setText(_translate("Dialog", "Track background colour", None))
        self.gridGroupBox.setTitle(_translate("Dialog", "Grid", None))
        self.gridOnCheckBox.setText(_translate("Dialog", "Grid displayed", None))
        self.gridColorLabel.setText(_translate("Dialog", "Grid colour", None))
        self.gridOpacityLabel.setText(_translate("Dialog", "Grid opacity", None))
        self.gridStyleLabel.setText(_translate("Dialog", "Grid line style", None))
        self.gridVerticalDivLabel.setToolTip(_translate("Dialog", "Number of vertical divisions for linear axis plots", None))
        self.gridVerticalDivLabel.setText(_translate("Dialog", "Vertical divisions", None))
        self.labelGroupBox.setTitle(_translate("Dialog", "Label", None))
        self.labelsExpandedCheckBox.setToolTip(_translate("Dialog", "Vertically expanded labels (better for long log names)", None))
        self.labelsExpandedCheckBox.setText(_translate("Dialog", "Expanded labels", None))
        self.labelBackgroundColorLabel.setText(_translate("Dialog", "Background colour", None))
        self.labelBackgroundOpacityLabel.setText(_translate("Dialog", "Background opacity", None))
        self.labelForegroundColorLabel.setText(_translate("Dialog", "Foreground colour", None))
        self.labelForegroundOpacityLabel.setText(_translate("Dialog", "Foreground opacity", None))
        self.styleTabWidget.setTabText(self.styleTabWidget.indexOf(self.plotStyleTab), _translate("Dialog", "Plot style", None))
        self.trackGroupBox_2.setTitle(_translate("Dialog", "Track size", None))
        self.trackWidthLabel.setText(_translate("Dialog", "Track width", None))
        self.trackGapLabel.setText(_translate("Dialog", "Track gap", None))
        self.trackApplyAllCheckBox.setText(_translate("Dialog", "Apply to all", None))
        self.styleTabWidget.setTabText(self.styleTabWidget.indexOf(self.trackStyleTab), _translate("Dialog", "Track style", None))
        self.styleTabWidget.setTabText(self.styleTabWidget.indexOf(self.curveStyleTab), _translate("Dialog", "Curve style", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.styleTab), _translate("Dialog", "Style", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("Dialog", "Data table", None))

