# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackstylewidget.ui'
#
# Created: Thu Jul  2 05:54:49 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TrackStyleWidget(object):
    def setupUi(self, TrackStyleWidget):
        TrackStyleWidget.setObjectName(_fromUtf8("TrackStyleWidget"))
        TrackStyleWidget.resize(500, 329)
        self.verticalLayout = QtGui.QVBoxLayout(TrackStyleWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.trackScrollArea = QtGui.QScrollArea(TrackStyleWidget)
        self.trackScrollArea.setWidgetResizable(True)
        self.trackScrollArea.setObjectName(_fromUtf8("trackScrollArea"))
        self.trackScrollAreaWidgetContents = QtGui.QWidget()
        self.trackScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 471, 84))
        self.trackScrollAreaWidgetContents.setObjectName(_fromUtf8("trackScrollAreaWidgetContents"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.trackScrollAreaWidgetContents)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.trackTableWidget = QtGui.QTableWidget(self.trackScrollAreaWidgetContents)
        self.trackTableWidget.setObjectName(_fromUtf8("trackTableWidget"))
        self.trackTableWidget.setColumnCount(0)
        self.trackTableWidget.setRowCount(0)
        self.horizontalLayout_15.addWidget(self.trackTableWidget)
        self.trackScrollArea.setWidget(self.trackScrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.trackScrollArea)
        self.trackNGridTabWidget = QtGui.QTabWidget(TrackStyleWidget)
        self.trackNGridTabWidget.setObjectName(_fromUtf8("trackNGridTabWidget"))
        self.trackSizeTab = QtGui.QWidget()
        self.trackSizeTab.setObjectName(_fromUtf8("trackSizeTab"))
        self.gridLayout = QtGui.QGridLayout(self.trackSizeTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.trackGroupBox = QtGui.QGroupBox(self.trackSizeTab)
        self.trackGroupBox.setTitle(_fromUtf8(""))
        self.trackGroupBox.setFlat(True)
        self.trackGroupBox.setObjectName(_fromUtf8("trackGroupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.trackGroupBox)
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.trackWidthLabel = QtGui.QLabel(self.trackGroupBox)
        self.trackWidthLabel.setObjectName(_fromUtf8("trackWidthLabel"))
        self.gridLayout_10.addWidget(self.trackWidthLabel, 2, 0, 1, 1)
        self.trackGapLabel = QtGui.QLabel(self.trackGroupBox)
        self.trackGapLabel.setObjectName(_fromUtf8("trackGapLabel"))
        self.gridLayout_10.addWidget(self.trackGapLabel, 3, 0, 1, 1)
        self.trackWidthLineEdit = QtGui.QLineEdit(self.trackGroupBox)
        self.trackWidthLineEdit.setObjectName(_fromUtf8("trackWidthLineEdit"))
        self.gridLayout_10.addWidget(self.trackWidthLineEdit, 2, 2, 1, 1)
        self.trackGapLineEdit = QtGui.QLineEdit(self.trackGroupBox)
        self.trackGapLineEdit.setObjectName(_fromUtf8("trackGapLineEdit"))
        self.gridLayout_10.addWidget(self.trackGapLineEdit, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(266, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 2, 1, 1, 1)
        self.trackApplyAllCheckBox = QtGui.QCheckBox(self.trackGroupBox)
        self.trackApplyAllCheckBox.setObjectName(_fromUtf8("trackApplyAllCheckBox"))
        self.gridLayout_10.addWidget(self.trackApplyAllCheckBox, 1, 0, 1, 1)
        self.trackGapUnitsComboBox = QtGui.QComboBox(self.trackGroupBox)
        self.trackGapUnitsComboBox.setObjectName(_fromUtf8("trackGapUnitsComboBox"))
        self.gridLayout_10.addWidget(self.trackGapUnitsComboBox, 3, 4, 1, 1)
        self.trackWidthUnitsComboBox = QtGui.QComboBox(self.trackGroupBox)
        self.trackWidthUnitsComboBox.setObjectName(_fromUtf8("trackWidthUnitsComboBox"))
        self.gridLayout_10.addWidget(self.trackWidthUnitsComboBox, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.trackGroupBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.trackNGridTabWidget.addTab(self.trackSizeTab, _fromUtf8(""))
        self.gridTab = QtGui.QWidget()
        self.gridTab.setObjectName(_fromUtf8("gridTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gridTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.applyGridToAllCheckBox = QtGui.QCheckBox(self.gridTab)
        self.applyGridToAllCheckBox.setObjectName(_fromUtf8("applyGridToAllCheckBox"))
        self.verticalLayout_3.addWidget(self.applyGridToAllCheckBox)
        self.widget_3 = QtGui.QWidget(self.gridTab)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.griidGroupBox = QtGui.QGroupBox(self.widget_3)
        self.griidGroupBox.setTitle(_fromUtf8(""))
        self.griidGroupBox.setFlat(True)
        self.griidGroupBox.setObjectName(_fromUtf8("griidGroupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.griidGroupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLineStyleComboBox = QtGui.QComboBox(self.griidGroupBox)
        self.gridLineStyleComboBox.setObjectName(_fromUtf8("gridLineStyleComboBox"))
        self.gridLayout_6.addWidget(self.gridLineStyleComboBox, 4, 2, 1, 1)
        self.gridColourLabel = QtGui.QLabel(self.griidGroupBox)
        self.gridColourLabel.setObjectName(_fromUtf8("gridColourLabel"))
        self.gridLayout_6.addWidget(self.gridColourLabel, 1, 0, 2, 1)
        self.gridOpacitySpinBox = QtGui.QSpinBox(self.griidGroupBox)
        self.gridOpacitySpinBox.setObjectName(_fromUtf8("gridOpacitySpinBox"))
        self.gridLayout_6.addWidget(self.gridOpacitySpinBox, 2, 2, 2, 1)
        self.gridOpacityLabel = QtGui.QLabel(self.griidGroupBox)
        self.gridOpacityLabel.setObjectName(_fromUtf8("gridOpacityLabel"))
        self.gridLayout_6.addWidget(self.gridOpacityLabel, 3, 0, 1, 1)
        self.gridColorPushButton = QtGui.QPushButton(self.griidGroupBox)
        self.gridColorPushButton.setText(_fromUtf8(""))
        self.gridColorPushButton.setObjectName(_fromUtf8("gridColorPushButton"))
        self.gridLayout_6.addWidget(self.gridColorPushButton, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.gridLineStyleLabel = QtGui.QLabel(self.griidGroupBox)
        self.gridLineStyleLabel.setObjectName(_fromUtf8("gridLineStyleLabel"))
        self.gridLayout_6.addWidget(self.gridLineStyleLabel, 4, 0, 1, 1)
        self.gridDisplayedCheckBox = QtGui.QCheckBox(self.griidGroupBox)
        self.gridDisplayedCheckBox.setObjectName(_fromUtf8("gridDisplayedCheckBox"))
        self.gridLayout_6.addWidget(self.gridDisplayedCheckBox, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.griidGroupBox)
        self.gridLogLinearGroupBox = QtGui.QGroupBox(self.widget_3)
        self.gridLogLinearGroupBox.setTitle(_fromUtf8(""))
        self.gridLogLinearGroupBox.setFlat(True)
        self.gridLogLinearGroupBox.setObjectName(_fromUtf8("gridLogLinearGroupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.gridLogLinearGroupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineaGridDivisionsLabel = QtGui.QLabel(self.gridLogLinearGroupBox)
        self.lineaGridDivisionsLabel.setObjectName(_fromUtf8("lineaGridDivisionsLabel"))
        self.horizontalLayout_5.addWidget(self.lineaGridDivisionsLabel)
        self.linearGridVerticalDivisionsSpinBox = QtGui.QSpinBox(self.gridLogLinearGroupBox)
        self.linearGridVerticalDivisionsSpinBox.setObjectName(_fromUtf8("linearGridVerticalDivisionsSpinBox"))
        self.horizontalLayout_5.addWidget(self.linearGridVerticalDivisionsSpinBox)
        self.logarithmicGridVerticalDivisionsLabel = QtGui.QLabel(self.gridLogLinearGroupBox)
        self.logarithmicGridVerticalDivisionsLabel.setObjectName(_fromUtf8("logarithmicGridVerticalDivisionsLabel"))
        self.horizontalLayout_5.addWidget(self.logarithmicGridVerticalDivisionsLabel)
        self.widget_2 = QtGui.QWidget(self.gridLogLinearGroupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.logarithmicGridVerticalDivisionsSpinBox = QtGui.QSpinBox(self.widget_2)
        self.logarithmicGridVerticalDivisionsSpinBox.setObjectName(_fromUtf8("logarithmicGridVerticalDivisionsSpinBox"))
        self.horizontalLayout_4.addWidget(self.logarithmicGridVerticalDivisionsSpinBox)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.gridLogLinearGroupBox)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.trackNGridTabWidget.addTab(self.gridTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.trackNGridTabWidget)

        self.retranslateUi(TrackStyleWidget)
        self.trackNGridTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TrackStyleWidget)

    def retranslateUi(self, TrackStyleWidget):
        TrackStyleWidget.setWindowTitle(_translate("TrackStyleWidget", "Form", None))
        self.trackWidthLabel.setText(_translate("TrackStyleWidget", "Track width", None))
        self.trackGapLabel.setText(_translate("TrackStyleWidget", "Track gap", None))
        self.trackApplyAllCheckBox.setText(_translate("TrackStyleWidget", "Apply to all tacks", None))
        self.trackNGridTabWidget.setTabText(self.trackNGridTabWidget.indexOf(self.trackSizeTab), _translate("TrackStyleWidget", "Track size", None))
        self.applyGridToAllCheckBox.setText(_translate("TrackStyleWidget", "Apply to all tracks", None))
        self.gridColourLabel.setText(_translate("TrackStyleWidget", "Grid colour", None))
        self.gridOpacityLabel.setText(_translate("TrackStyleWidget", "Grid opacity", None))
        self.gridLineStyleLabel.setText(_translate("TrackStyleWidget", "Grid line style", None))
        self.gridDisplayedCheckBox.setText(_translate("TrackStyleWidget", "Show grid", None))
        self.lineaGridDivisionsLabel.setText(_translate("TrackStyleWidget", "Linear grid vertical divisions", None))
        self.logarithmicGridVerticalDivisionsLabel.setText(_translate("TrackStyleWidget", "Logathmic grid vertical divisions", None))
        self.trackNGridTabWidget.setTabText(self.trackNGridTabWidget.indexOf(self.gridTab), _translate("TrackStyleWidget", "Grid style", None))

