# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wellplotstylewidget.ui'
#
# Created: Thu Jul  2 18:40:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WellPlotStyleWidget(object):
    def setupUi(self, WellPlotStyleWidget):
        WellPlotStyleWidget.setObjectName(_fromUtf8("WellPlotStyleWidget"))
        WellPlotStyleWidget.resize(400, 300)
        self.horizontalLayout = QtGui.QHBoxLayout(WellPlotStyleWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.wellPlotStyleOuterWidget = QtGui.QWidget(WellPlotStyleWidget)
        self.wellPlotStyleOuterWidget.setObjectName(_fromUtf8("wellPlotStyleOuterWidget"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.wellPlotStyleOuterWidget)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.wellPlotStyleWidget = QtGui.QWidget(self.wellPlotStyleOuterWidget)
        self.wellPlotStyleWidget.setObjectName(_fromUtf8("wellPlotStyleWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wellPlotStyleWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.plotTitleWidget = QtGui.QWidget(self.wellPlotStyleWidget)
        self.plotTitleWidget.setObjectName(_fromUtf8("plotTitleWidget"))
        self.gridLayout = QtGui.QGridLayout(self.plotTitleWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.plotTitleOnCheckBox = QtGui.QCheckBox(self.plotTitleWidget)
        self.plotTitleOnCheckBox.setObjectName(_fromUtf8("plotTitleOnCheckBox"))
        self.gridLayout.addWidget(self.plotTitleOnCheckBox, 0, 0, 1, 2)
        self.plotTitleLabel = QtGui.QLabel(self.plotTitleWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTitleLabel.sizePolicy().hasHeightForWidth())
        self.plotTitleLabel.setSizePolicy(sizePolicy)
        self.plotTitleLabel.setObjectName(_fromUtf8("plotTitleLabel"))
        self.gridLayout.addWidget(self.plotTitleLabel, 1, 0, 1, 1)
        self.plotTitleLineEdit = QtGui.QLineEdit(self.plotTitleWidget)
        self.plotTitleLineEdit.setMaximumSize(QtCore.QSize(276, 16777215))
        self.plotTitleLineEdit.setObjectName(_fromUtf8("plotTitleLineEdit"))
        self.gridLayout.addWidget(self.plotTitleLineEdit, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.plotTitleWidget)
        self.widget_5 = QtGui.QWidget(self.wellPlotStyleWidget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.plotBackgroundOpacityLabel = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBackgroundOpacityLabel.sizePolicy().hasHeightForWidth())
        self.plotBackgroundOpacityLabel.setSizePolicy(sizePolicy)
        self.plotBackgroundOpacityLabel.setObjectName(_fromUtf8("plotBackgroundOpacityLabel"))
        self.gridLayout_4.addWidget(self.plotBackgroundOpacityLabel, 1, 0, 1, 1)
        self.plotBackgroundColorLabel = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBackgroundColorLabel.sizePolicy().hasHeightForWidth())
        self.plotBackgroundColorLabel.setSizePolicy(sizePolicy)
        self.plotBackgroundColorLabel.setObjectName(_fromUtf8("plotBackgroundColorLabel"))
        self.gridLayout_4.addWidget(self.plotBackgroundColorLabel, 0, 0, 1, 1)
        self.trackBackgroundOpacitySpinBox = QtGui.QSpinBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackBackgroundOpacitySpinBox.sizePolicy().hasHeightForWidth())
        self.trackBackgroundOpacitySpinBox.setSizePolicy(sizePolicy)
        self.trackBackgroundOpacitySpinBox.setObjectName(_fromUtf8("trackBackgroundOpacitySpinBox"))
        self.gridLayout_4.addWidget(self.trackBackgroundOpacitySpinBox, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.trackBGColourBtnHolderWidget = QtGui.QWidget(self.widget_5)
        self.trackBGColourBtnHolderWidget.setObjectName(_fromUtf8("trackBGColourBtnHolderWidget"))
        self.gridLayout_4.addWidget(self.trackBGColourBtnHolderWidget, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.headerLabelWidget = QtGui.QWidget(self.wellPlotStyleWidget)
        self.headerLabelWidget.setObjectName(_fromUtf8("headerLabelWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.headerLabelWidget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.singleRowLabelsCheckBox = QtGui.QCheckBox(self.headerLabelWidget)
        self.singleRowLabelsCheckBox.setObjectName(_fromUtf8("singleRowLabelsCheckBox"))
        self.gridLayout_5.addWidget(self.singleRowLabelsCheckBox, 0, 0, 1, 1)
        self.labelBackgroundColorLabel = QtGui.QLabel(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBackgroundColorLabel.sizePolicy().hasHeightForWidth())
        self.labelBackgroundColorLabel.setSizePolicy(sizePolicy)
        self.labelBackgroundColorLabel.setObjectName(_fromUtf8("labelBackgroundColorLabel"))
        self.gridLayout_5.addWidget(self.labelBackgroundColorLabel, 1, 0, 1, 1)
        self.labelForegroundOpacitySpinBox = QtGui.QSpinBox(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelForegroundOpacitySpinBox.sizePolicy().hasHeightForWidth())
        self.labelForegroundOpacitySpinBox.setSizePolicy(sizePolicy)
        self.labelForegroundOpacitySpinBox.setObjectName(_fromUtf8("labelForegroundOpacitySpinBox"))
        self.gridLayout_5.addWidget(self.labelForegroundOpacitySpinBox, 4, 2, 1, 1)
        self.labelBackgroundOpacityLabel = QtGui.QLabel(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBackgroundOpacityLabel.sizePolicy().hasHeightForWidth())
        self.labelBackgroundOpacityLabel.setSizePolicy(sizePolicy)
        self.labelBackgroundOpacityLabel.setObjectName(_fromUtf8("labelBackgroundOpacityLabel"))
        self.gridLayout_5.addWidget(self.labelBackgroundOpacityLabel, 2, 0, 1, 1)
        self.labelBackgroundOpacitySpinBox = QtGui.QSpinBox(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBackgroundOpacitySpinBox.sizePolicy().hasHeightForWidth())
        self.labelBackgroundOpacitySpinBox.setSizePolicy(sizePolicy)
        self.labelBackgroundOpacitySpinBox.setObjectName(_fromUtf8("labelBackgroundOpacitySpinBox"))
        self.gridLayout_5.addWidget(self.labelBackgroundOpacitySpinBox, 2, 2, 1, 1)
        self.labelForegroundColorLabel = QtGui.QLabel(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelForegroundColorLabel.sizePolicy().hasHeightForWidth())
        self.labelForegroundColorLabel.setSizePolicy(sizePolicy)
        self.labelForegroundColorLabel.setObjectName(_fromUtf8("labelForegroundColorLabel"))
        self.gridLayout_5.addWidget(self.labelForegroundColorLabel, 3, 0, 1, 1)
        self.labelForegroundOpacityLabel = QtGui.QLabel(self.headerLabelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelForegroundOpacityLabel.sizePolicy().hasHeightForWidth())
        self.labelForegroundOpacityLabel.setSizePolicy(sizePolicy)
        self.labelForegroundOpacityLabel.setObjectName(_fromUtf8("labelForegroundOpacityLabel"))
        self.gridLayout_5.addWidget(self.labelForegroundOpacityLabel, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        self.headerLabelBGColourBtnHolderWidget = QtGui.QWidget(self.headerLabelWidget)
        self.headerLabelBGColourBtnHolderWidget.setObjectName(_fromUtf8("headerLabelBGColourBtnHolderWidget"))
        self.gridLayout_5.addWidget(self.headerLabelBGColourBtnHolderWidget, 1, 2, 1, 1)
        self.headerLabelTextColourBtnHolderWidget = QtGui.QWidget(self.headerLabelWidget)
        self.headerLabelTextColourBtnHolderWidget.setObjectName(_fromUtf8("headerLabelTextColourBtnHolderWidget"))
        self.gridLayout_5.addWidget(self.headerLabelTextColourBtnHolderWidget, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.headerLabelWidget)
        spacerItem3 = QtGui.QSpacerItem(20, 136, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_19.addWidget(self.wellPlotStyleWidget)
        self.horizontalLayout.addWidget(self.wellPlotStyleOuterWidget)

        self.retranslateUi(WellPlotStyleWidget)
        QtCore.QMetaObject.connectSlotsByName(WellPlotStyleWidget)

    def retranslateUi(self, WellPlotStyleWidget):
        WellPlotStyleWidget.setWindowTitle(_translate("WellPlotStyleWidget", "Form", None))
        self.plotTitleOnCheckBox.setText(_translate("WellPlotStyleWidget", "Plot title displayed", None))
        self.plotTitleLabel.setText(_translate("WellPlotStyleWidget", "Plot title", None))
        self.plotBackgroundOpacityLabel.setText(_translate("WellPlotStyleWidget", "Track background opacity", None))
        self.plotBackgroundColorLabel.setText(_translate("WellPlotStyleWidget", "Track background colour", None))
        self.singleRowLabelsCheckBox.setToolTip(_translate("WellPlotStyleWidget", "Fit labels to a single row", None))
        self.singleRowLabelsCheckBox.setText(_translate("WellPlotStyleWidget", "Single row header labels", None))
        self.labelBackgroundColorLabel.setText(_translate("WellPlotStyleWidget", "Header label background colour", None))
        self.labelBackgroundOpacityLabel.setText(_translate("WellPlotStyleWidget", "Header label background opacity", None))
        self.labelForegroundColorLabel.setText(_translate("WellPlotStyleWidget", "Header label text colour", None))
        self.labelForegroundOpacityLabel.setText(_translate("WellPlotStyleWidget", "Header label text opacity", None))

