# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrbase_view.ui'
#
# Created: Fri Nov 14 17:49:22 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(795, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Insert = QtGui.QMenu(self.menubar)
        self.menu_Insert.setObjectName(_fromUtf8("menu_Insert"))
        self.menu_Project = QtGui.QMenu(self.menubar)
        self.menu_Project.setObjectName(_fromUtf8("menu_Project"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        self.menu_Window = QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName(_fromUtf8("menu_Window"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarTop = QtGui.QToolBar(MainWindow)
        self.toolBarTop.setObjectName(_fromUtf8("toolBarTop"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarTop)
        self.toolBarBottom = QtGui.QToolBar(MainWindow)
        self.toolBarBottom.setObjectName(_fromUtf8("toolBarBottom"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBarBottom)
        self.dockWidgetData = QtGui.QDockWidget(MainWindow)
        self.dockWidgetData.setObjectName(_fromUtf8("dockWidgetData"))
        self.dockWidgetContentsInput = QtGui.QWidget()
        self.dockWidgetContentsInput.setObjectName(_fromUtf8("dockWidgetContentsInput"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContentsInput)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidgetInput = QtGui.QTabWidget(self.dockWidgetContentsInput)
        self.tabWidgetInput.setObjectName(_fromUtf8("tabWidgetInput"))
        self.tabInput = QtGui.QWidget()
        self.tabInput.setObjectName(_fromUtf8("tabInput"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabInput)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.treeWidgetInput = QtGui.QTreeWidget(self.tabInput)
        self.treeWidgetInput.setObjectName(_fromUtf8("treeWidgetInput"))
        self.treeWidgetInput.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_6.addWidget(self.treeWidgetInput, 0, 0, 1, 1)
        self.tabWidgetInput.addTab(self.tabInput, _fromUtf8(""))
        self.tabOptional = QtGui.QWidget()
        self.tabOptional.setObjectName(_fromUtf8("tabOptional"))
        self.tabWidgetInput.addTab(self.tabOptional, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidgetInput)
        self.dockWidgetData.setWidget(self.dockWidgetContentsInput)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetData)
        self.dockWidgetProcess = QtGui.QDockWidget(MainWindow)
        self.dockWidgetProcess.setObjectName(_fromUtf8("dockWidgetProcess"))
        self.dockWidgetContentsProcess = QtGui.QWidget()
        self.dockWidgetContentsProcess.setObjectName(_fromUtf8("dockWidgetContentsProcess"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContentsProcess)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidgetProcess = QtGui.QTabWidget(self.dockWidgetContentsProcess)
        self.tabWidgetProcess.setObjectName(_fromUtf8("tabWidgetProcess"))
        self.tabProcess = QtGui.QWidget()
        self.tabProcess.setObjectName(_fromUtf8("tabProcess"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabProcess)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.treeWidgetProcess = QtGui.QTreeWidget(self.tabProcess)
        self.treeWidgetProcess.setObjectName(_fromUtf8("treeWidgetProcess"))
        self.treeWidgetProcess.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_7.addWidget(self.treeWidgetProcess, 0, 0, 1, 1)
        self.tabWidgetProcess.addTab(self.tabProcess, _fromUtf8(""))
        self.tabWindow = QtGui.QWidget()
        self.tabWindow.setObjectName(_fromUtf8("tabWindow"))
        self.tabWidgetProcess.addTab(self.tabWindow, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidgetProcess, 0, 0, 1, 1)
        self.dockWidgetProcess.setWidget(self.dockWidgetContentsProcess)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetProcess)
        self.toolBarRHS = QtGui.QToolBar(MainWindow)
        self.toolBarRHS.setObjectName(_fromUtf8("toolBarRHS"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBarRHS)
        self.dockWidgetMessage = QtGui.QDockWidget(MainWindow)
        self.dockWidgetMessage.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidgetMessage.setObjectName(_fromUtf8("dockWidgetMessage"))
        self.dockWidgetContentsMessage = QtGui.QWidget()
        self.dockWidgetContentsMessage.setObjectName(_fromUtf8("dockWidgetContentsMessage"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContentsMessage)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidgetMessages = QtGui.QTabWidget(self.dockWidgetContentsMessage)
        self.tabWidgetMessages.setObjectName(_fromUtf8("tabWidgetMessages"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 725, 99))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.textBrowserMessages = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowserMessages.setObjectName(_fromUtf8("textBrowserMessages"))
        self.horizontalLayout_4.addWidget(self.textBrowserMessages)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.tabWidgetMessages.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidgetMessages.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidgetMessages)
        self.dockWidgetMessage.setWidget(self.dockWidgetContentsMessage)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMessage)
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionImport_file = QtGui.QAction(MainWindow)
        self.actionImport_file.setObjectName(_fromUtf8("actionImport_file"))
        self.actionSave_project = QtGui.QAction(MainWindow)
        self.actionSave_project.setObjectName(_fromUtf8("actionSave_project"))
        self.actionSave_project_as = QtGui.QAction(MainWindow)
        self.actionSave_project_as.setObjectName(_fromUtf8("actionSave_project_as"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action2D_window = QtGui.QAction(MainWindow)
        self.action2D_window.setObjectName(_fromUtf8("action2D_window"))
        self.action3D_window = QtGui.QAction(MainWindow)
        self.action3D_window.setObjectName(_fromUtf8("action3D_window"))
        self.actionLog_plot_window = QtGui.QAction(MainWindow)
        self.actionLog_plot_window.setObjectName(_fromUtf8("actionLog_plot_window"))
        self.actionWell_correlation_window = QtGui.QAction(MainWindow)
        self.actionWell_correlation_window.setObjectName(_fromUtf8("actionWell_correlation_window"))
        self.actionX_Y_plot_window = QtGui.QAction(MainWindow)
        self.actionX_Y_plot_window.setObjectName(_fromUtf8("actionX_Y_plot_window"))
        self.actionX_Y_Z_plot_window = QtGui.QAction(MainWindow)
        self.actionX_Y_Z_plot_window.setObjectName(_fromUtf8("actionX_Y_Z_plot_window"))
        self.menu_File.addAction(self.actionNew_project)
        self.menu_File.addAction(self.actionOpen_project)
        self.menu_File.addAction(self.actionImport_file)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave_project)
        self.menu_File.addAction(self.actionSave_project_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Window.addAction(self.action2D_window)
        self.menu_Window.addAction(self.action3D_window)
        self.menu_Window.addAction(self.actionLog_plot_window)
        self.menu_Window.addAction(self.actionWell_correlation_window)
        self.menu_Window.addAction(self.actionX_Y_plot_window)
        self.menu_Window.addAction(self.actionX_Y_Z_plot_window)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Insert.menuAction())
        self.menubar.addAction(self.menu_Project.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetInput.setCurrentIndex(1)
        self.tabWidgetProcess.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Insert.setTitle(QtGui.QApplication.translate("MainWindow", "&Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Project.setTitle(QtGui.QApplication.translate("MainWindow", "&Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(QtGui.QApplication.translate("MainWindow", "&Window", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarTop.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarBottom.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabInput), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetInput.setTabText(self.tabWidgetInput.indexOf(self.tabOptional), QtGui.QApplication.translate("MainWindow", "Optional", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProcess.setTabText(self.tabWidgetProcess.indexOf(self.tabProcess), QtGui.QApplication.translate("MainWindow", "Processes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProcess.setTabText(self.tabWidgetProcess.indexOf(self.tabWindow), QtGui.QApplication.translate("MainWindow", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarRHS.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMessages.setTabText(self.tabWidgetMessages.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMessages.setTabText(self.tabWidgetMessages.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_project.setText(QtGui.QApplication.translate("MainWindow", "New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_project.setText(QtGui.QApplication.translate("MainWindow", "Open project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_file.setText(QtGui.QApplication.translate("MainWindow", "Import file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_project.setText(QtGui.QApplication.translate("MainWindow", "Save project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_project_as.setText(QtGui.QApplication.translate("MainWindow", "Save project as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action2D_window.setText(QtGui.QApplication.translate("MainWindow", "2D window", None, QtGui.QApplication.UnicodeUTF8))
        self.action3D_window.setText(QtGui.QApplication.translate("MainWindow", "3D window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_plot_window.setText(QtGui.QApplication.translate("MainWindow", "Log plot window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWell_correlation_window.setText(QtGui.QApplication.translate("MainWindow", "Well correlation window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_Y_plot_window.setText(QtGui.QApplication.translate("MainWindow", "X/Y plot window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionX_Y_Z_plot_window.setText(QtGui.QApplication.translate("MainWindow", "X/Y/Z plot window", None, QtGui.QApplication.UnicodeUTF8))

